# Generated by Django 5.2.5 on 2026-02-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('from_station', models.CharField(max_length=50)),
                ('to_station', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=20)),
                ('arrival', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('train_type', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('amenities', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='Train.train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='Train.train')),
            ],
        ),
    ]
